### ISSUE TITLE
CLUTNet中的forward函数

### ISSUE THREAD

**Issue by ChengJDeng** [Xian-Bei/CLUT-Net#3]
请问为什么CLUTNet中的forward函数返回的是img_res + img_org呢？

**Comment by Xian-Bei** [comment]
So that the network only needs to learn the additional enhancement effects instead of the entire enhanced results (just a common residual thought, does not really matter).

**Comment by ChengJDeng** [comment]
Thanks, it seems to be a much more effective way than the way learning the entire enhanced results directly.
