### ISSUE TITLE
About tvmn loss of training

### ISSUE THREAD

**Issue by YangGangZhiQi** [Xian-Bei/CLUT-Net#5]
Hi, thanks for this novel works. I am trying to training CLUT-Net on my computer with FiveK datasets. When starting training, I find the tvmn loss is nearly equal to zero(about 1e-8). Dose it normal, or Is there something wrong with my training config?

   
![tvmn_loss](https://github.com/Xian-Bei/CLUT-Net/assets/87355944/417dce59-5918-4b03-a6a0-9c5e2d6bc6a0)

**Comment by Xian-Bei** [comment]
Sorry for the late reply. It is normal since we initialize the basis CLUTs as zero. 
Thanks for your interest!
