### ISSUE TITLE
can you provide the codes for prepraing hdrplus dataset?

### ISSUE THREAD

**Issue by simpler66** [Xian-Bei/CLUT-Net#7]
Do you know how to convert raw data to xyz colorspace

**Comment by Xian-Bei** [comment]
We directly utilize the processed HDR+ dataset provided by [Image-Adaptive-3DLUT](https://github.com/HuiZeng/Image-Adaptive-3DLUT). However, they have detailed the processing procedure in Section 4.1 of their paper, which might interest you. Regarding the conversion of color space, would software like Lightroom suffice for your needs? Hope it helps.

**Comment by simpler66** [comment]
thanks for your reply. I have tried rawpy (mentioned in the paper) to generate input data in XYZ space, however the generated data seem different from those provided by [Image-Adaptive-3DLUT](https://github.com/HuiZeng/Image-Adaptive-3DLUT).

**Comment by Xian-Bei** [comment]
I understand that processing the HDR+ dataset can be somewhat tricky due to some alignment issues, but I apologize for not being helpful; I'm not very familiar with the details.
