### ISSUE TITLE
Can you provide the code for the Grid occupancy visualization?

### ISSUE THREAD

**Issue by leemojiang** [Xian-Bei/CLUT-Net#8]
Could you please provide the visulization code for grid occupancy? I didn't find them in the /utils files.

**Comment by Xian-Bei** [comment]
Sorry for the missing. I've found it and uploaded it as 'utils/occupied_grid_visualization.py' through the webpage. 
Hope it helps.

**Comment by leemojiang** [comment]
Thank you very much.
